zbirenbaum/copilot.lua

lua/copilot/util.lua
=> protocol fix for #24

lua/copilot/suggestion.lua
What you see should be what you get.
---
**Before**
**After**
---
**Before**
**After**
--- 
**Before**
**After**
---
**Before**
**After**
---
**Before**
**After**
=> fix(suggestion): weird indentation after .accept

lua/copilot/suggestion.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/72
=> fix(suggestion): do not toggle insert mode on accept

plugin/copilot.lua
https://github.com/zbirenbaum/copilot.lua/issues/82
=> fix(command): :Copilot without params

lua/copilot/init.lua
resolves https://github.com/zbirenbaum/copilot.lua/issues/94
=> fix: ignore consecutive setup calls

lua/copilot/auth.lua, lua/copilot/client.lua, lua/copilot/command.lua, lua/copilot/config.lua, lua/copilot/init.lua, lua/copilot/panel.lua, lua/copilot/suggestion.lua, lua/copilot/util.lua, plugin/copilot.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/100
=> feat(client): improved start and attach

README.md, lua/copilot/util.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/111
=> feat: support function for filetypes

lua/copilot/panel.lua
resolves https://github.com/zbirenbaum/copilot.lua/issues/116
=> fix(panel): go back to correct place after accept

lua/copilot/panel.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/97
=> fix(panel): display lines extra indent strip

lua/copilot/suggestion.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/130
=> fix(suggestion): virtual text flicker

lua/copilot/client.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/132
=> feat(client): check node executable before setup

lua/copilot/client.lua, lua/copilot/command.lua, lua/copilot/config.lua, lua/copilot/init.lua, lua/copilot/panel.lua, lua/copilot/suggestion.lua, plugin/copilot.lua
resolves https://github.com/zbirenbaum/copilot.lua/issues/74
=> feat(command): add attach, detach, enable, disable

lua/copilot/suggestion.lua
resolves https://github.com/zbirenbaum/copilot.lua/issues/135
=> fix(suggestion): allow next/prev to schedule with auto_trigger=true

README.md, lua/copilot/api.lua, lua/copilot/suggestion.lua
This will allow user to modify the accepted suggestion before inserting.
Related to: https://github.com/zbirenbaum/copilot.lua/issues/151
=> feat(suggestion): support suggestion modifier for .accept

lua/copilot/api.lua, lua/copilot/client.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/145
=> fix(api): set_editor_info method

lua/copilot/suggestion.lua
=> Make dismiss a noop when Copilot isn't visible

lua/copilot/command.lua, lua/copilot/util.lua
=> feat: stop using 'copilot.vim' in editorPluginInfo

lua/copilot/suggestion.lua
=> fix(suggestion): cursor position for nvim v0.10.x

README.md
Hi,
Recently I made a plugin which integrates lualine and copilot.lua.
`This integration is just an icon which can be customized to show the status of copilot.lua`
I thought it will be good to document for ease of finding.
I hope this helps anyone who needs it. 
You can check it out here -> [AndreM222/copilot-lualine](https://github.com/AndreM222/copilot-lualine)
=> docs(lualine): lualine integration plugin

lua/copilot/api.lua, lua/copilot/client.lua, lua/copilot/config.lua
- update copilot, switch from agent.js to language-server.js
- add auth provider url option and support, similiar to #296
=> Update copilot and add authProvider url option

lua/copilot/panel.lua
=> fix: panel error with index local 'id'

README.md, lua/copilot/client.lua, lua/copilot/config.lua
Used to determine if Copilot should attach to a buffer or not. Fixes: #74
=> feat: add should_attach function

README.md
Add documentation for `auth_provider_url` in README.md
=> document auth_provider_url setting

.github/workflows/update-copilot-nodejs.yaml, README.md
- Formatting of the caution part.
- Typos.
- Added a table of contents to make navigation easier.
=> fix(docs): fix typos, add table of contents, add faq
