- copilot/index.js
`#!/bin/node` is reliant on `node` being installed in`/bin`
MacOS doesn't have `node` at that location (at least not for me). `#!/usr/bin/env node` uses the `node` set in `PATH`, so  this should work for all Linux/macOS environments.
Thanks for making this repo, and I hope it's not weird that I made this PR! 😅
> fix: Language server not executable

- README.md
- lua/copilot/config.lua
- lua/copilot/init.lua
- lua/copilot/util.lua
Hi, 
first of all, great work. This plugin was released exactly as I got my Copilot access and fits so much better into my workflow than the official alternative. So thank you.
The problem is, it doesn't work with my setup, since you assume Packer as package management solution, which I don't use yet. To make this plugin package manager or rather installation path agnostic, I changed the way the Copilot path finding works and while I was at it, I made the whole plugin more extendable and idiomatic to current NeoVim Plugin conventions by introduction a `setup` function for easy customization.
Most modern nvim plugins have such a function to, as the name suggests, setup the plugin's functionality.
e.g. [Telescope](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/ini …
> Fixed the vim-pack incompatability and improved configuration

- lua/copilot/util.lua
E5108: Error executing lua ...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: Vim(append):Error executing lua callback: ...r/neovim/HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp.lua:1217: client_id: expected number, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
...r/neovim/HEAD-8f95f3e/share/nvim/runtime/lua/vim/lsp.lua:1217: in function 'buf_attach_client'
...im/site/pack/packer/opt/copilot.lua/lua/copilot/util.lua:33: in function 'attach_copilot'
...k/packer/opt/copilot.lua/lua/copilot/copilot_handler.lua:19: in function <...k/packer/opt/copilot.lua/lua/copilot/copilot_handler.lua:18>
[C]: in function 'nvim_set_current_win'
...ack/packer/start/plenary.nvim/lua/plenary/popup/init.lua:408: in function 'create' …
> fix: null client_id when init lsp

- lua/copilot/client.lua
The new API requires a `{ bufnr = bufnr }`. It will validate for table and
throw error for number values: `filter: expected table, got number`.
> fix(client): missing bufnr for get_active_clients

- lua/copilot/client.lua
The `filter` option to `vim.lsp.get_active_clients()` is not available in 0.7 and earlier.
> Fix attaching to buffer on Neovim < 0.8

- README.md
- lua/copilot/client.lua
- lua/copilot/init.lua
- lua/copilot/util.lua
We can get the plugin directory directly instead of searching from the pack manager path. This can make the life of users that don't use packer a bit easier.
See https://neovim.discourse.group/t/get-path-to-plugin-directory/2658
> remove pack_manager_path

- lua/copilot/api.lua
- lua/copilot/auth.lua
- lua/copilot/client.lua
- lua/copilot/util.lua
- util changes to follow the `copilot.vim` behavior closely
- ~panel changes to make it more extensible~
- `copilot.api` module can be used by any plugins that want to implement UI for `copilot.lua`
The APIs can be used in two flavors:
**Callback**
```lua
local sent, request_id = require("copilot.api").check_status(client, function(err, data, ctx)
print(vim.inspect({ err = err, data = data, ctx = ctx })
end)
```
**Coroutine**
```lua
coroutine.wrap(function()
local err, data, ctx = require("copilot.api").check_status(client)
print(vim.inspect({ err = err, data = data, ctx = ctx })
end)()
```
---
I'll be creating followup PRs to make the panel fully functional.
> feat: add copilot.api module

- README.md
- lua/copilot/highlight.lua
- lua/copilot/init.lua
- lua/copilot/suggestion.lua
Depends on:
- https://github.com/zbirenbaum/copilot.lua/pull/48
---
Integration with external plugins possible with these functions:
```lua
require("copilot.suggestion").is_visible()
require("copilot.suggestion").accept()
require("copilot.suggestion").next()
require("copilot.suggestion").prev()
require("copilot.suggestion").dismiss()
require("copilot.suggestion").toggle_auto_trigger()
```
For example, with `nvim-cmp` use `<Tab>` to accept suggestion when it's visible:
```lua
cmp.setup({
-- ...
mapping = {
-- ...
["<Tab>"] = cmp.mapping(function(fallback)
if require("copilot.suggestion").is_visible() then
require("copilot.suggestion").accept()
elseif cmp.visible() then
cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
elseif luasnip.expandable() then
luasnip.expand()
elseif …
```
> feat: add copilot.suggestion module

- README.md
- lua/copilot/client.lua
- lua/copilot/init.lua
Resolves #51
Specify filetypes for attaching copilot.
Default (same as `copilot.vim`):
```lua
filetypes = {
yaml = false,
markdown = false,
help = false,
gitcommit = false,
gitrebase = false,
hgcommit = false,
svn = false,
cvs = false,
["."] = false, -- usually include secrets (e.g. dotfiles, .env* files)
},
```
Example:
```lua
require("copilot").setup {
filetypes = {
markdown = true, -- overrides default
terraform = false, -- disallow specific filetype
},
}
```
If you add `"*"` as a filetype, the default configuration for `filetypes` won't be used anymore. e.g.
```lua
require("copilot").setup {
filetypes = {
javascript = true, -- allow specific filetype
typescript = true, -- allow specific filetype
["*"] = false, -- disable for all other filetypes and ignore default `filetypes`
},
}
```
> feat: support 'filetypes' option

- README.md
- lua/copilot/config.lua
- lua/copilot/suggestion.lua
- plugin/copilot.lua
Resolves https://github.com/zbirenbaum/copilot.lua/issues/85
```lua
require("copilot").setup({
suggestion = {
keymap = {
accept_word = "<M-Right>",
accept_line = "<M-Down>",
},
},
})
```
> feat(suggestion): support partial accept

- README.md
- plugin/copilot.lua
Documenting too many options in README.md is causing users to run into weird edge-cases with lazy loading.
Also wait for copilot server to start when `:Copilot` command is run.
> Simplify lazy loading instructions and wait for Copilot to start

- README.md
- lua/copilot/config.lua
- lua/copilot/panel.lua
Add config options for default panel split and size behavior. Adds optional table parameter to `panel.open` where these options can be overriden for use in keymaps.
Implements zbirenbaum/copilot.lua#103
> Add panel ui options

- lua/copilot/client.lua
`systemlist ` return 
``` 
**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.5.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
v18.16.0
```
on `powershell`
so, should get last element in the `systemlist` result, or use a more precise regex.
> fix(client): always get error node version on `powershell`

- lua/copilot/client.lua
get_node_version() was not working for me with a custom vim.opt.shell.
Using a table instead of a concatenation solved the issue.
> get_node_version() not working with custom vim.opt.shell

- README.md
Related to #225 
Recent update has changed the minimum node version from 16.x to 18.x
This isn't reflected in the README
> docs: Update min. node version in README

- lua/copilot/panel.lua
- lua/copilot/suggestion.lua
> fix apply_text_edits implicit bufnr 

- README.md
- lua/copilot/config.lua
- lua/copilot/suggestion.lua
I like to always see the shadow text even when completion menu is open. Other integrations like intellij one have this as option as well.
> Add option to disable auto hide on pumvisible

- lua/copilot/command.lua
- lua/copilot/suggestion.lua
- **fix: rename agent.js to language-server.js**
- **fix: enable nvim v0.10 features in v0.11+ versions**
> Update Copilot to use language-server.js

- copilot/package.json
Closes #306
I tested this by:
1. creating a `package.json` in my home dir
2. adding `"type": "module"`
3. opening nvim and see copilot crash
4. adding the `package.json` see in the diff to `~/.local/share/nvim/lazy/copilot.lua/copilot/package.json`
5. open nvim
6. observed no crashes 🥳
> fix: esm package traversal

- lua/copilot/suggestion.lua
As described in issue #278 - when you are set up in like SuperTab, you get this error (E565) from the LSP util that you're not allowed to modify the buffer.
The TL;DR here (**I think**) is that you're trying to do a synchronous accept with the results from an asynchronous call.  The solution is to enqueue the accept on the event loop so that the text edit happens on the next tick (after whatever already enqueued async calls have already happened) rather than trying to do it on the "main thread"
> Fix E565 when using Tab as accept

- lua/copilot/api.lua
> Feat: Implement openURL

- lua/copilot/suggestion.lua
These changes ensure that the text edits are applied using the correct encoding for the current buffer, improving compatibility with different file encodings.
The changes made in the `suggestion.lua` file are as follows:
1. **Dynamic Encoding Retrieval**:
- The code now dynamically retrieves the file encoding of the current buffer using `vim.api.nvim_get_option_value('fileencoding', { buf = bufnr })`.
- This replaces the previous hardcoded "utf-16" encoding.
2. **Buffer Number Handling**:
- The current buffer number is stored in the `bufnr` variable using `vim.api.nvim_get_current_buf()`.
- This buffer number is then used to retrieve the encoding and apply text edits.
> fix: wrong buffer encoding breaks accepting suggestions

- lua/copilot/panel.lua
Whenever the Copilot LSP knows it's not going to provide any suggestions, it replies with PanelSolutionsDone even before it completes the request. This resulted in us setting the status to "done" and then immediately resetting it to "loading", and thus getting stuck on "loading".
The fix is to set the status to "loading" in the initial refresh call itself to avoid the race between on_solutions_done and the get_panel_completions callback.
> fix(panel): avoid being stuck "loading"

- lua/copilot/util.lua
`not vim.bo.buftype == ""` means `(not vim.bo.buftype) == ""` in Lua…
> fix: only attach to normal buffers

- README.md
- lua/copilot/panel.lua
The "bottom" and "right" options create full-width splits. This change adds options to split only the current window horizontally or vertically, which is the default vim behavior when splitting.
> Support non-full-width horizontal and vertical splits

- lua/copilot/suggestion.lua
This fix addresses an issue where an error occurs if the buffer's `fileencoding` option is empty during certain operations, such as applying text edits in the LSP. (#344)
While similar issues regarding file encodings have been reported and resolved, this specific case occurs when the `fileencoding` of a buffer is not explicitly set. In such cases, the empty string (`""`) is returned, leading to failures in functions that expect a valid encoding (e.g., `vim.lsp.util.apply_text_edits`).
- Added a fallback mechanism to use the global `encoding` option (`vim.o.encoding`) if `fileencoding` is empty.
- Ensured that the user’s configuration for `encoding` is respected before defaulting to `"utf-8"`.
1. Open a new file in Neovim (e.g., `nvim newfile.txt`).
2. Without saving the file or setting …
> fix: Handle empty fileencoding by falling back to global encoding

- lua/copilot/suggestion.lua
This pull request make that the suggestion get triggered when entering insert mode.
It was not working because both `InsertEnter` and `CursorMovedI` would fire at the same time and the timer variable would be messed up in the debounce function like this:
- `InsertEnter` is called, `copilot.timer` is set to timer id 1
- `CursorMovedI` is called, `copilot.timer` is set to timer id 2
- Debounce function 1 is called, `timer` is 1, `copilot.timer` is 2, early return, `copilot.timer` is set to `nil`
- Debounce function 2 is called, `timer` is 2, `copilot.timer` is `nil`, early return
This pull requests fixes this, I'm testing this since yesterday and it's working fine, but I don't know the codebase very well so I'm hoping I'm not breaking something.
Also the debounce function doesn't seem to be …
> fix(suggestion): Trigger suggestion on InsertEnter

- lua/copilot/client.lua
add `--stdio` to end of command. Having some trouble with getting completions to appear even though executable is running so may have to revert #372
> fix missing stdio param

- lua/copilot/client.lua
- lua/copilot/suggestion.lua
No PR dependencies on this one, seemed like a simple race condition with the async setEditorInfo call happening after trying to get suggestions.
fixes #321
> fix: prevent agent service not initialized

- lua/copilot/client.lua
- lua/copilot/logger.lua
- Stop old client instance instead of erroring when multiple servers are started
- Replace deprecated vim.loop with vim.uv
background: #386
> (Ready)fix: handle multiple copilot server instances

- lua/copilot/client.lua
- lua/copilot/logger.lua
Some LSP servers like jsonlsp don't support window/logMessage method, causing potential errors. Move the handler to client config to avoid this. 
Fixes #389
> fix: avoid LSP error with unsupported window/logMessage

- README.md
- lua/copilot/client.lua
- lua/copilot/config.lua
- lua/copilot/logger.lua
You will need to manually turn on the logs if you would like to see them, as there are quite a bit of warnings and errors already present in the LSP logs which users have not had to worry about, making this too much of a sudden change.
Fixes #391
> fix: don't capture LSP logs by default & filter Copilot logs

- README.md
It took me a while to figure this one out, and since blink.cmp is rapidly gaining popularity, I thought it may be beneficial to also add an auto-hiding solution for this plugin next to nvim-cmp.
> Recipe to automatically hide Copilot suggestions for blink.cmp

- lua/copilot/api.lua
- lua/copilot/client.lua
- lua/copilot/logger.lua
- lua/copilot/suggestion.lua
Add tracing logs, ensure logTrace enables it in the LSP and cancel the suggestion debounce timer when a new request is sent to prevent calling the LSP multiple times for the same info.
> logging and performance improvements

- lua/copilot/lsp_binary.lua
Hello,
I just saw you reverted the changes, but this pull request could be used as a base to make the integration with the official binaries. Maybe we can work a little on this one to create the `beta` branch you were mentioning in https://github.com/zbirenbaum/copilot.lua/issues/408
Official binaries do not work on `musl` systems (ie. *alpine* or *void*). This PR detects the libc setting and fallbacks to the default js language-server. 
Maybe, we can add a configuration option to allow users to decide to use the `js` version rather than the binary.
**NB**: i left commented the download functions for a different PR
> fix: Using js server when on musl

- .github/dependabot.yml
- .github/workflows/vimdocgen.yml
- README.md
> feat: add vimdoc with ci, add dependabot config for automatic updates of ci, fix docs typo

- README.md
- doc/copilot.txt
- lua/copilot/panel/init.lua
In doc and README.md comments, and in .../panel/init.lua, change possible position values to match validation values in .../lua/copilot/config/panel.lua so as to avoid validation error on "horizontal' or "vertical".
Note: indeed, "horizontal" and "vertical" add no functionality.
> doc, README.md and .../panel/init.lua panel positions

- lua/copilot/client/init.lua
- lua/copilot/command.lua
- lua/copilot/util.lua
> fix: use buf for FileType autocmd

- lua/copilot/suggestion/init.lua
The suggestion's next-function automatically starts again from the beginning after having reached the last completion. 
As there is no way to prevent this behaviour with the current interface or configuration, a `has_next()` method was added, returning false when there are no further suggestions.
This allows code like
```lua
if cop.has_next() then
cop.next()
end
```
The cycling to be skipped without side-effects that direct modification of `next()` could have.
Use-case: show all copilot suggestions. When all were shown, then show the LSP completion menu
> Allow to skip cycling on suggestion.next()

- lua/copilot/lsp/nodejs.lua
Fixes previous commit of splitting copilot_node_command 
Tested locally using
```
copilot_node_command = vim.fn.expand("$FNM_DIR") .. "/node-versions/v22.13.0/installation/bin/node",
```
> fix: Fixes splitting of copilot_node_command

- tests/stubs/nodejs.lua
I assume this doesn't have much of an effect but I noticed it when debugging an issue with another plugin.
> fix: global `M` in test stub
